/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.assignment.bank;

import java.awt.Font;
import java.util.ArrayList;

/**
 *
 * @author Vj
 */
public class Numpad_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Login_Panel
     */
    
    static Option_Panel new_opt;
    static String disp_in;
    static String in_disp;
    static Integer in_size;
    static Integer in_key;
    static Integer val;
    static ArrayList<Integer> in;

    void display_message()
    {
        info_panel.setText(in_disp);
    }
    
    void get_val()
    {
        Integer multiplier = 1;
        val = 0;
        Integer[] in_val = Numpad_Panel.in.toArray(new Integer[Numpad_Panel.in.size()]);
        for (int i = Numpad_Panel.in.size()-1; i>=0; i--)
        {
            val = val + (in_val[i] * multiplier);
            multiplier = multiplier * 10;
        }
    }
    
    void lock_panel()
    {
        num_1_btn.setEnabled(false);
        num_2_btn.setEnabled(false);
        num_3_btn.setEnabled(false);
        num_4_btn.setEnabled(false);
        num_5_btn.setEnabled(false);
        num_6_btn.setEnabled(false);
        num_7_btn.setEnabled(false);
        num_8_btn.setEnabled(false);
        num_9_btn.setEnabled(false);
        num_0_btn.setEnabled(false);
        enter_btn.setEnabled(false);
        back_btn.setEnabled(false);
        clear_btn.setEnabled(false);
    }
    
    void input()
    {
        
        switch (Main_Driver.opt) {    
            case "pin_ck":
                disp_in = "<html><p style=\"text-align:center;\">";
                in.forEach((_item) -> {
                    disp_in = disp_in + " /* ";
                }); break;
            case "acc_ck":
            case "depo":
            case "with":
            case "pay":
                if (in.isEmpty())
                {
                    disp_in = "";
                }
                else
                {
                    get_val();
                    disp_in = ""+val;
                }
                break;
            default:
        }
        
        info_panel.setText(in_disp+disp_in);
    }
    
    public Numpad_Panel() {
        initComponents();
        this.setBounds(Main_Driver.position);
        info_panel.setFont(Main_Driver.font.deriveFont(Font.PLAIN, 24f));
        in = new ArrayList<>();
        if ("acc_ck".equals(Main_Driver.opt))
            back_btn.setVisible(false);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        enter_btn = new javax.swing.JButton();
        num_3_btn = new javax.swing.JButton();
        num_2_btn = new javax.swing.JButton();
        num_1_btn = new javax.swing.JButton();
        num_4_btn = new javax.swing.JButton();
        num_5_btn = new javax.swing.JButton();
        num_6_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        num_7_btn = new javax.swing.JButton();
        num_8_btn = new javax.swing.JButton();
        num_9_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        num_0_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        info_panel = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 640));
        setResizable(false);

        enter_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        enter_btn.setForeground(new java.awt.Color(0, 204, 0));
        enter_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/med_btn.png"))); // NOI18N
        enter_btn.setText("ENTER");
        enter_btn.setBorderPainted(false);
        enter_btn.setContentAreaFilled(false);
        enter_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_btnActionPerformed(evt);
            }
        });

        num_3_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num_3_btn.setForeground(new java.awt.Color(255, 255, 255));
        num_3_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/sml_btn.png"))); // NOI18N
        num_3_btn.setText("3");
        num_3_btn.setBorderPainted(false);
        num_3_btn.setContentAreaFilled(false);
        num_3_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num_3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_3_btnActionPerformed(evt);
            }
        });

        num_2_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num_2_btn.setForeground(new java.awt.Color(255, 255, 255));
        num_2_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/sml_btn.png"))); // NOI18N
        num_2_btn.setText("2");
        num_2_btn.setBorderPainted(false);
        num_2_btn.setContentAreaFilled(false);
        num_2_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num_2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_2_btnActionPerformed(evt);
            }
        });

        num_1_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num_1_btn.setForeground(new java.awt.Color(255, 255, 255));
        num_1_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/sml_btn.png"))); // NOI18N
        num_1_btn.setText("1");
        num_1_btn.setBorderPainted(false);
        num_1_btn.setContentAreaFilled(false);
        num_1_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num_1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_1_btnActionPerformed(evt);
            }
        });

        num_4_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num_4_btn.setForeground(new java.awt.Color(255, 255, 255));
        num_4_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/sml_btn.png"))); // NOI18N
        num_4_btn.setText("4");
        num_4_btn.setBorderPainted(false);
        num_4_btn.setContentAreaFilled(false);
        num_4_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num_4_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_4_btnActionPerformed(evt);
            }
        });

        num_5_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num_5_btn.setForeground(new java.awt.Color(255, 255, 255));
        num_5_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/sml_btn.png"))); // NOI18N
        num_5_btn.setText("5");
        num_5_btn.setBorderPainted(false);
        num_5_btn.setContentAreaFilled(false);
        num_5_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num_5_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_5_btnActionPerformed(evt);
            }
        });

        num_6_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num_6_btn.setForeground(new java.awt.Color(255, 255, 255));
        num_6_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/sml_btn.png"))); // NOI18N
        num_6_btn.setText("6");
        num_6_btn.setBorderPainted(false);
        num_6_btn.setContentAreaFilled(false);
        num_6_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num_6_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_6_btnActionPerformed(evt);
            }
        });

        clear_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(255, 204, 0));
        clear_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/med_btn.png"))); // NOI18N
        clear_btn.setText("CLEAR");
        clear_btn.setBorderPainted(false);
        clear_btn.setContentAreaFilled(false);
        clear_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        num_7_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num_7_btn.setForeground(new java.awt.Color(255, 255, 255));
        num_7_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/sml_btn.png"))); // NOI18N
        num_7_btn.setText("7");
        num_7_btn.setBorderPainted(false);
        num_7_btn.setContentAreaFilled(false);
        num_7_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num_7_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_7_btnActionPerformed(evt);
            }
        });

        num_8_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num_8_btn.setForeground(new java.awt.Color(255, 255, 255));
        num_8_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/sml_btn.png"))); // NOI18N
        num_8_btn.setText("8");
        num_8_btn.setBorderPainted(false);
        num_8_btn.setContentAreaFilled(false);
        num_8_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num_8_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_8_btnActionPerformed(evt);
            }
        });

        num_9_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num_9_btn.setForeground(new java.awt.Color(255, 255, 255));
        num_9_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/sml_btn.png"))); // NOI18N
        num_9_btn.setText("9");
        num_9_btn.setBorderPainted(false);
        num_9_btn.setContentAreaFilled(false);
        num_9_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num_9_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_9_btnActionPerformed(evt);
            }
        });

        cancel_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancel_btn.setForeground(new java.awt.Color(255, 0, 0));
        cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/med_btn.png"))); // NOI18N
        cancel_btn.setText("CANCEL");
        cancel_btn.setBorderPainted(false);
        cancel_btn.setContentAreaFilled(false);
        cancel_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        num_0_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        num_0_btn.setForeground(new java.awt.Color(255, 255, 255));
        num_0_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/sml_btn.png"))); // NOI18N
        num_0_btn.setText("0");
        num_0_btn.setBorderPainted(false);
        num_0_btn.setContentAreaFilled(false);
        num_0_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        num_0_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_0_btnActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/med_btn.png"))); // NOI18N
        back_btn.setText("BACK");
        back_btn.setBorderPainted(false);
        back_btn.setContentAreaFilled(false);
        back_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        info_panel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        info_panel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info_panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/num_panel.png"))); // NOI18N
        info_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        info_panel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num_7_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(num_4_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(num_1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num_2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(num_5_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(num_8_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(num_0_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num_6_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_3_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_9_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(2, 2, 2))))
                    .addComponent(info_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {num_0_btn, num_2_btn, num_3_btn, num_4_btn, num_5_btn, num_6_btn, num_7_btn, num_8_btn, num_9_btn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(info_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num_3_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_2_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_1_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num_4_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_5_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_6_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(num_9_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(num_8_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(num_7_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(num_0_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {num_0_btn, num_7_btn, num_8_btn, num_9_btn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num_1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_1_btnActionPerformed
        if (in.size()<in_size)
        {
            in_key = 1;
            in.add(in_key);
            input();
        }
    }//GEN-LAST:event_num_1_btnActionPerformed

    private void num_2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_2_btnActionPerformed
        if (in.size()<in_size)
        {
            in_key = 2;
            in.add(in_key);
            input();
        }
    }//GEN-LAST:event_num_2_btnActionPerformed

    private void num_3_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_3_btnActionPerformed
        if (in.size()<in_size)
        {
            in_key = 3;
            in.add(in_key);
            input();
        }
    }//GEN-LAST:event_num_3_btnActionPerformed

    private void num_4_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_4_btnActionPerformed
        if (in.size()<in_size)
        {
            in_key = 4;
            in.add(in_key);
            input();
        }
    }//GEN-LAST:event_num_4_btnActionPerformed

    private void num_5_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_5_btnActionPerformed
        if (in.size()<in_size)
        {
            in_key = 5;
            in.add(in_key);
            input();
        }
    }//GEN-LAST:event_num_5_btnActionPerformed

    private void num_6_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_6_btnActionPerformed
        if (in.size()<in_size)
        {
            in_key = 6;
            in.add(in_key);
            input();
        }
    }//GEN-LAST:event_num_6_btnActionPerformed

    private void num_7_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_7_btnActionPerformed
        if (in.size()>in_size)
        {
            in_key = 7;
            in.add(in_key);
            input();
        }
    }//GEN-LAST:event_num_7_btnActionPerformed

    private void num_8_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_8_btnActionPerformed
        if (in.size()<in_size)
        {
            in_key = 8;
            in.add(in_key);
            input();
        }
    }//GEN-LAST:event_num_8_btnActionPerformed

    private void num_9_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_9_btnActionPerformed
        if (in.size()<in_size)
        {
            in_key = 9;
            in.add(in_key);
            input();
        }
    }//GEN-LAST:event_num_9_btnActionPerformed

    private void num_0_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_0_btnActionPerformed
        if (in.size()<in_size)
        {
            in_key = 0;
            in.add(in_key);
            input();
        }
    }//GEN-LAST:event_num_0_btnActionPerformed

    private void enter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_btnActionPerformed
        Main_Driver.position = this.getBounds();
        if (null != Main_Driver.opt)
        switch (Main_Driver.opt) {
            case "acc_ck":
                Main_Process.pros_acc_num();
                break;
            case "pin_ck":
                Main_Process.pros_acc_pin();
                break;
            case "depo":
                Option_Panel.opt_disp = "<html><p style=\"text-align:center;\"><html>CONFIRM DEPOSIT OF<br><br>FJD <html>"+Numpad_Panel.in.toString();
                new Option_Panel().setVisible(true);
                this.setVisible(false);
                break;
            case "with":
                Option_Panel.opt_disp = "<html><p style=\"text-align:center;\"><html>CONFIRM WITHDRAWAL OF<br><br>FJD <html>"+Numpad_Panel.in.toString();
                new Option_Panel().setVisible(true);
                this.setVisible(false);
                break;
            default:
                break;
        }
        enter_btn.setEnabled(false);
    }//GEN-LAST:event_enter_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        in.clear();
        input();
    }//GEN-LAST:event_clear_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        Main_Driver.position = this.getBounds();
        Main_Driver.acc_num = null;
        new Home_Panel().setVisible(true);
        cancel_btn.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        Main_Driver.position = this.getBounds();
        if (null!= Main_Driver.opt)
        switch (Main_Driver.opt) {
            case "depo":
            case "with":
                new Menu_Panel().setVisible(true);
                this.setVisible(false);
                break;
            default:
                break;
        } 
        back_btn.setEnabled(false);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Numpad_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Numpad_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Numpad_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Numpad_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Numpad_Panel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton enter_btn;
    private javax.swing.JLabel info_panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton num_0_btn;
    private javax.swing.JButton num_1_btn;
    private javax.swing.JButton num_2_btn;
    private javax.swing.JButton num_3_btn;
    private javax.swing.JButton num_4_btn;
    private javax.swing.JButton num_5_btn;
    private javax.swing.JButton num_6_btn;
    private javax.swing.JButton num_7_btn;
    private javax.swing.JButton num_8_btn;
    private javax.swing.JButton num_9_btn;
    // End of variables declaration//GEN-END:variables
}
