/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.assignment.bank;

import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vj
 */
public class Record_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Option_Panel
     */
    
 
    void set_date()
    {
        Main_Driver.date_srt = ""+from_YYYY.getText()+"-"+from_MM.getText()+"-"+from_DD.getText()+" 00:00:00";
        Main_Driver.date_end = ""+to_YYYY.getText()+"-"+to_MM.getText()+"-"+to_DD.getText()+" 23:59:59";
    }
    
    void lock_panel()
    {
        from_YYYY.setEnabled(false);
        from_MM.setEnabled(false);
        from_DD.setEnabled(false);
        to_YYYY.setEnabled(false);
        to_MM.setEnabled(false);
        to_DD.setEnabled(false);
        send_btn.setEnabled(false);
    }
      
    public Record_Panel() {
        initComponents();
        this.setBounds(Main_Driver.position);
        rec_disp.setFont(Main_Driver.font.deriveFont(Font.PLAIN, 24f));
        rec_disp.setText("<html><p style=\"text-align:center;\"> PLEASE ENTER START DATE <br><br> END DATE AND <br><br> EMAIL ADDRESS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancel_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        rec_panel = new javax.swing.JPanel();
        send_btn = new javax.swing.JButton();
        from_label = new javax.swing.JLabel();
        from_DD = new javax.swing.JTextField();
        end_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        from_MM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        from_YYYY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        to_DD = new javax.swing.JTextField();
        to_MM = new javax.swing.JTextField();
        to_YYYY = new javax.swing.JTextField();
        email_add = new javax.swing.JTextField();
        rec_disp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 640));
        setMinimumSize(new java.awt.Dimension(480, 640));
        setResizable(false);

        cancel_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/med_btn_2.png"))); // NOI18N
        cancel_btn.setText("CANCEL");
        cancel_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/med_btn_2.png"))); // NOI18N
        back_btn.setText("BACK");
        back_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        rec_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        send_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        send_btn.setForeground(new java.awt.Color(255, 255, 255));
        send_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/assignment/bank/images/lrg_btn_2.png"))); // NOI18N
        send_btn.setText("EXPORT TO EMAIL");
        send_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });

        from_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        from_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        from_label.setText("START DATE");

        from_DD.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        from_DD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        from_DD.setText("DD");

        end_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        end_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        end_label.setText("END DATE");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("/");

        from_MM.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        from_MM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        from_MM.setText("MM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("/");

        from_YYYY.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        from_YYYY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        from_YYYY.setText("YYYY");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("/");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("/");

        to_DD.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        to_DD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        to_DD.setText("DD");

        to_MM.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        to_MM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        to_MM.setText("MM");

        to_YYYY.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        to_YYYY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        to_YYYY.setText("YYYY");

        email_add.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email_add.setText("EMAIL ADDRESS");

        javax.swing.GroupLayout rec_panelLayout = new javax.swing.GroupLayout(rec_panel);
        rec_panel.setLayout(rec_panelLayout);
        rec_panelLayout.setHorizontalGroup(
            rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rec_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rec_panelLayout.createSequentialGroup()
                        .addGroup(rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rec_panelLayout.createSequentialGroup()
                                .addComponent(from_DD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(from_MM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(from_YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(from_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rec_panelLayout.createSequentialGroup()
                                .addComponent(to_DD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(to_MM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(to_YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(end_label, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(email_add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rec_panelLayout.createSequentialGroup()
                        .addComponent(send_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rec_panelLayout.setVerticalGroup(
            rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rec_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(from_DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(from_MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(from_YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rec_panelLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(rec_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(to_DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(to_MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(to_YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(end_label)
                        .addComponent(from_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(send_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        rec_disp.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rec_disp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rec_disp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        rec_disp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rec_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rec_disp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(rec_disp, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(rec_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        Main_Driver.position = this.getBounds();
        new Menu_Panel().setVisible(true);
        back_btn.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        Main_Driver.position = this.getBounds();
        Main_Driver.acc_num = null;
        new Home_Panel().setVisible(true);
        cancel_btn.setEnabled(false);        
        this.setVisible(false);
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        set_date();
        try
        {
            String email = email_add.getText();
            rec_disp.setText("<html><p style=\"text-align:center;\"> >>> SENDING EMAIL >>>");
            Main_Driver.bankObj.getTransactions(Main_Driver.acc_num, Main_Driver.date_srt, Main_Driver.date_end, email);
            rec_disp.setText("<html><p style=\"text-align:center;\"> EMAIL SENT ");
            
        }
        catch (Exception ex)
        {
            Logger.getLogger(Record_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        send_btn.setEnabled(false);
    }//GEN-LAST:event_send_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Record_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Record_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Record_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Record_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Record_Panel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JTextField email_add;
    private javax.swing.JLabel end_label;
    private javax.swing.JTextField from_DD;
    private javax.swing.JTextField from_MM;
    private javax.swing.JTextField from_YYYY;
    private javax.swing.JLabel from_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel rec_disp;
    private javax.swing.JPanel rec_panel;
    private javax.swing.JButton send_btn;
    private javax.swing.JTextField to_DD;
    private javax.swing.JTextField to_MM;
    private javax.swing.JTextField to_YYYY;
    // End of variables declaration//GEN-END:variables
}
