package BankServerApp;


/**
* BankServerApp/BankServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankServer.idl
* Friday, October 11, 2019 10:45:23 AM FJT
*/

abstract public class BankServerHelper
{
  private static String  _id = "IDL:BankServerApp/BankServer:1.0";

  public static void insert (org.omg.CORBA.Any a, BankServerApp.BankServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BankServerApp.BankServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BankServerApp.BankServerHelper.id (), "BankServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BankServerApp.BankServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BankServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BankServerApp.BankServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BankServerApp.BankServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BankServerApp.BankServer)
      return (BankServerApp.BankServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BankServerApp._BankServerStub stub = new BankServerApp._BankServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BankServerApp.BankServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BankServerApp.BankServer)
      return (BankServerApp.BankServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BankServerApp._BankServerStub stub = new BankServerApp._BankServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
