package BankServerApp;


/**
* BankServerApp/BankServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankServer.idl
* Friday, October 11, 2019 10:45:23 AM FJT
*/

public interface BankServerOperations 
{
  boolean checkAcntNum (int acntNum);
  boolean checkAcntStatus (int acntNum);
  boolean verifyAcntPin (int acntNum, int acntPin);
  void lockAcnt (int acntNum);
  void makeDeposit (int acntNum, int amount);
  void makeWithdrawal (int acntNum, int amount);
  double checkBalance (int acntNum);
  boolean checkOverdraft (int acntNum, double amount);
  void getTransactions (int acntNum, String startDate, String endDate, String emailAddr);
} // interface BankServerOperations
