package BankServerApp;

/**
* BankServerApp/BankServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankServer.idl
* Friday, October 11, 2019 10:45:23 AM FJT
*/

public final class BankServerHolder implements org.omg.CORBA.portable.Streamable
{
  public BankServerApp.BankServer value = null;

  public BankServerHolder ()
  {
  }

  public BankServerHolder (BankServerApp.BankServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankServerApp.BankServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankServerApp.BankServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankServerApp.BankServerHelper.type ();
  }

}
