package BankServerApp;


/**
* BankServerApp/BankServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankServer.idl
* Friday, October 11, 2019 10:45:23 AM FJT
*/

public interface BankServer extends BankServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BankServer
